// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: v1/deeptrace.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeepTraceService_GetRecentLogs_FullMethodName    = "/v1.DeepTraceService/GetRecentLogs"
	DeepTraceService_GetProcessStacks_FullMethodName = "/v1.DeepTraceService/GetProcessStacks"
	DeepTraceService_RestartServer_FullMethodName    = "/v1.DeepTraceService/RestartServer"
	DeepTraceService_GetVersion_FullMethodName       = "/v1.DeepTraceService/GetVersion"
)

// DeepTraceServiceClient is the client API for DeepTraceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Debugging and diagnostic service
type DeepTraceServiceClient interface {
	// Get the most recent n lines of logs
	GetRecentLogs(ctx context.Context, in *GetRecentLogsRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Get process stack information by process type
	GetProcessStacks(ctx context.Context, in *GetProcessStacksRequest, opts ...grpc.CallOption) (*ProcessStacksResponse, error)
	// Restart server
	RestartServer(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	// Get version information
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type deepTraceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeepTraceServiceClient(cc grpc.ClientConnInterface) DeepTraceServiceClient {
	return &deepTraceServiceClient{cc}
}

func (c *deepTraceServiceClient) GetRecentLogs(ctx context.Context, in *GetRecentLogsRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, DeepTraceService_GetRecentLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deepTraceServiceClient) GetProcessStacks(ctx context.Context, in *GetProcessStacksRequest, opts ...grpc.CallOption) (*ProcessStacksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessStacksResponse)
	err := c.cc.Invoke(ctx, DeepTraceService_GetProcessStacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deepTraceServiceClient) RestartServer(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, DeepTraceService_RestartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deepTraceServiceClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, DeepTraceService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeepTraceServiceServer is the server API for DeepTraceService service.
// All implementations must embed UnimplementedDeepTraceServiceServer
// for forward compatibility.
//
// Debugging and diagnostic service
type DeepTraceServiceServer interface {
	// Get the most recent n lines of logs
	GetRecentLogs(context.Context, *GetRecentLogsRequest) (*LogResponse, error)
	// Get process stack information by process type
	GetProcessStacks(context.Context, *GetProcessStacksRequest) (*ProcessStacksResponse, error)
	// Restart server
	RestartServer(context.Context, *RestartRequest) (*RestartResponse, error)
	// Get version information
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedDeepTraceServiceServer()
}

// UnimplementedDeepTraceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeepTraceServiceServer struct{}

func (UnimplementedDeepTraceServiceServer) GetRecentLogs(context.Context, *GetRecentLogsRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentLogs not implemented")
}
func (UnimplementedDeepTraceServiceServer) GetProcessStacks(context.Context, *GetProcessStacksRequest) (*ProcessStacksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessStacks not implemented")
}
func (UnimplementedDeepTraceServiceServer) RestartServer(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartServer not implemented")
}
func (UnimplementedDeepTraceServiceServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedDeepTraceServiceServer) mustEmbedUnimplementedDeepTraceServiceServer() {}
func (UnimplementedDeepTraceServiceServer) testEmbeddedByValue()                          {}

// UnsafeDeepTraceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeepTraceServiceServer will
// result in compilation errors.
type UnsafeDeepTraceServiceServer interface {
	mustEmbedUnimplementedDeepTraceServiceServer()
}

func RegisterDeepTraceServiceServer(s grpc.ServiceRegistrar, srv DeepTraceServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeepTraceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeepTraceService_ServiceDesc, srv)
}

func _DeepTraceService_GetRecentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeepTraceServiceServer).GetRecentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeepTraceService_GetRecentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeepTraceServiceServer).GetRecentLogs(ctx, req.(*GetRecentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeepTraceService_GetProcessStacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessStacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeepTraceServiceServer).GetProcessStacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeepTraceService_GetProcessStacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeepTraceServiceServer).GetProcessStacks(ctx, req.(*GetProcessStacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeepTraceService_RestartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeepTraceServiceServer).RestartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeepTraceService_RestartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeepTraceServiceServer).RestartServer(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeepTraceService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeepTraceServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeepTraceService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeepTraceServiceServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DeepTraceService_ServiceDesc is the grpc.ServiceDesc for DeepTraceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeepTraceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DeepTraceService",
	HandlerType: (*DeepTraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecentLogs",
			Handler:    _DeepTraceService_GetRecentLogs_Handler,
		},
		{
			MethodName: "GetProcessStacks",
			Handler:    _DeepTraceService_GetProcessStacks_Handler,
		},
		{
			MethodName: "RestartServer",
			Handler:    _DeepTraceService_RestartServer_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _DeepTraceService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/deeptrace.proto",
}

const (
	AlertService_GetAlerts_FullMethodName = "/v1.AlertService/GetAlerts"
)

// AlertServiceClient is the client API for AlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertServiceClient interface {
	// Client gets alert summary
	GetAlerts(ctx context.Context, in *GetAlertsRequest, opts ...grpc.CallOption) (*GetAlertsResponse, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) GetAlerts(ctx context.Context, in *GetAlertsRequest, opts ...grpc.CallOption) (*GetAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertsResponse)
	err := c.cc.Invoke(ctx, AlertService_GetAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility.
type AlertServiceServer interface {
	// Client gets alert summary
	GetAlerts(context.Context, *GetAlertsRequest) (*GetAlertsResponse, error)
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertServiceServer struct{}

func (UnimplementedAlertServiceServer) GetAlerts(context.Context, *GetAlertsRequest) (*GetAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlerts not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}
func (UnimplementedAlertServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertServiceServer will
// result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_GetAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_GetAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlerts(ctx, req.(*GetAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlerts",
			Handler:    _AlertService_GetAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/deeptrace.proto",
}
