// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/deeptrace.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Log level enumeration
type LogLevel int32

const (
	LogLevel_LOG_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_DEBUG       LogLevel = 1
	LogLevel_LOG_INFO        LogLevel = 2
	LogLevel_LOG_WARNING     LogLevel = 3
	LogLevel_LOG_ERROR       LogLevel = 4
	LogLevel_LOG_CRITICAL    LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_UNSPECIFIED",
		1: "LOG_DEBUG",
		2: "LOG_INFO",
		3: "LOG_WARNING",
		4: "LOG_ERROR",
		5: "LOG_CRITICAL",
	}
	LogLevel_value = map[string]int32{
		"LOG_UNSPECIFIED": 0,
		"LOG_DEBUG":       1,
		"LOG_INFO":        2,
		"LOG_WARNING":     3,
		"LOG_ERROR":       4,
		"LOG_CRITICAL":    5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_deeptrace_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_v1_deeptrace_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{0}
}

// Process type enumeration
type ProcessType int32

const (
	ProcessType_PROCESS_UNSPECIFIED ProcessType = 0
	ProcessType_PROCESS_TRAINER     ProcessType = 1 // Trainer process
	ProcessType_PROCESS_DATA_LOADER ProcessType = 2 // Data loader process
	ProcessType_PROCESS_LAUNCHER    ProcessType = 3 // Launch process
)

// Enum value maps for ProcessType.
var (
	ProcessType_name = map[int32]string{
		0: "PROCESS_UNSPECIFIED",
		1: "PROCESS_TRAINER",
		2: "PROCESS_DATA_LOADER",
		3: "PROCESS_LAUNCHER",
	}
	ProcessType_value = map[string]int32{
		"PROCESS_UNSPECIFIED": 0,
		"PROCESS_TRAINER":     1,
		"PROCESS_DATA_LOADER": 2,
		"PROCESS_LAUNCHER":    3,
	}
)

func (x ProcessType) Enum() *ProcessType {
	p := new(ProcessType)
	*p = x
	return p
}

func (x ProcessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_deeptrace_proto_enumTypes[1].Descriptor()
}

func (ProcessType) Type() protoreflect.EnumType {
	return &file_v1_deeptrace_proto_enumTypes[1]
}

func (x ProcessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessType.Descriptor instead.
func (ProcessType) EnumDescriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{1}
}

// Error status codes
type ErrorCode int32

const (
	ErrorCode_ERROR_UNKNOWN              ErrorCode = 0
	ErrorCode_ERROR_INVALID_PROCESS_TYPE ErrorCode = 1
	ErrorCode_ERROR_PROCESS_NOT_FOUND    ErrorCode = 2
	ErrorCode_ERROR_LOG_SOURCE_NOT_FOUND ErrorCode = 3
	ErrorCode_ERROR_PERMISSION_DENIED    ErrorCode = 4
	ErrorCode_ERROR_SNAPSHOT_FAILED      ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_INVALID_PROCESS_TYPE",
		2: "ERROR_PROCESS_NOT_FOUND",
		3: "ERROR_LOG_SOURCE_NOT_FOUND",
		4: "ERROR_PERMISSION_DENIED",
		5: "ERROR_SNAPSHOT_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_UNKNOWN":              0,
		"ERROR_INVALID_PROCESS_TYPE": 1,
		"ERROR_PROCESS_NOT_FOUND":    2,
		"ERROR_LOG_SOURCE_NOT_FOUND": 3,
		"ERROR_PERMISSION_DENIED":    4,
		"ERROR_SNAPSHOT_FAILED":      5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_deeptrace_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v1_deeptrace_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{2}
}

type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_WARNING  Severity = 1
	Severity_ERROR    Severity = 2
	Severity_CRITICAL Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"ERROR":    2,
		"CRITICAL": 3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_deeptrace_proto_enumTypes[3].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_v1_deeptrace_proto_enumTypes[3]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{3}
}

// Single log entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // Log timestamp
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=v1.LogLevel" json:"level,omitempty"` // Log level
	Epoch         int32                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // Log content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_v1_deeptrace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_UNSPECIFIED
}

func (x *LogEntry) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RankLog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rank           string                 `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"`                                            // Rank number
	Entries        []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`                                      // Log entries
	SuspendSeconds int32                  `protobuf:"varint,3,opt,name=suspend_seconds,json=suspendSeconds,proto3" json:"suspend_seconds,omitempty"` // Interval (in seconds) between the last line of log for this rank and the collection time
	TailTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=tail_time,json=tailTime,proto3" json:"tail_time,omitempty"`                    // Log timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RankLog) Reset() {
	*x = RankLog{}
	mi := &file_v1_deeptrace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankLog) ProtoMessage() {}

func (x *RankLog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankLog.ProtoReflect.Descriptor instead.
func (*RankLog) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{1}
}

func (x *RankLog) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *RankLog) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RankLog) GetSuspendSeconds() int32 {
	if x != nil {
		return x.SuspendSeconds
	}
	return 0
}

func (x *RankLog) GetTailTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TailTime
	}
	return nil
}

// Request to get recent logs
type GetRecentLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxLines      int32                  `protobuf:"varint,1,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"`
	WorkDir       string                 `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentLogsRequest) Reset() {
	*x = GetRecentLogsRequest{}
	mi := &file_v1_deeptrace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLogsRequest) ProtoMessage() {}

func (x *GetRecentLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLogsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentLogsRequest) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentLogsRequest) GetMaxLines() int32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

func (x *GetRecentLogsRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

// Log response
type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranklogs      []*RankLog             `protobuf:"bytes,1,rep,name=ranklogs,proto3" json:"ranklogs,omitempty"` // Rank logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_v1_deeptrace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{3}
}

func (x *LogResponse) GetRanklogs() []*RankLog {
	if x != nil {
		return x.Ranklogs
	}
	return nil
}

// Single thread stack information
type ThreadStack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      int32                  `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`         // Thread ID
	ThreadName    string                 `protobuf:"bytes,2,opt,name=thread_name,json=threadName,proto3" json:"thread_name,omitempty"`    // Thread name
	StackFrames   []string               `protobuf:"bytes,3,rep,name=stack_frames,json=stackFrames,proto3" json:"stack_frames,omitempty"` // Stack frame list (most recent first)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStack) Reset() {
	*x = ThreadStack{}
	mi := &file_v1_deeptrace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStack) ProtoMessage() {}

func (x *ThreadStack) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStack.ProtoReflect.Descriptor instead.
func (*ThreadStack) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{4}
}

func (x *ThreadStack) GetThreadId() int32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *ThreadStack) GetThreadName() string {
	if x != nil {
		return x.ThreadName
	}
	return ""
}

func (x *ThreadStack) GetStackFrames() []string {
	if x != nil {
		return x.StackFrames
	}
	return nil
}

// Single process information
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`                       // Process ID
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`                     // Parent process ID
	Type          ProcessType            `protobuf:"varint,3,opt,name=type,proto3,enum=v1.ProcessType" json:"type,omitempty"` // Process type
	Threads       []*ThreadStack         `protobuf:"bytes,4,rep,name=threads,proto3" json:"threads,omitempty"`                // Thread stack information
	Rank          string                 `protobuf:"bytes,5,opt,name=rank,proto3" json:"rank,omitempty"`
	LocalRank     string                 `protobuf:"bytes,6,opt,name=local_rank,json=localRank,proto3" json:"local_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_v1_deeptrace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetType() ProcessType {
	if x != nil {
		return x.Type
	}
	return ProcessType_PROCESS_UNSPECIFIED
}

func (x *ProcessInfo) GetThreads() []*ThreadStack {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ProcessInfo) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *ProcessInfo) GetLocalRank() string {
	if x != nil {
		return x.LocalRank
	}
	return ""
}

type ProcessInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfoList) Reset() {
	*x = ProcessInfoList{}
	mi := &file_v1_deeptrace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfoList) ProtoMessage() {}

func (x *ProcessInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfoList.ProtoReflect.Descriptor instead.
func (*ProcessInfoList) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessInfoList) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessInfoList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request to get process stacks
type GetProcessStacksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target process type (required)
	ProcessType ProcessType `protobuf:"varint,1,opt,name=process_type,json=processType,proto3,enum=v1.ProcessType" json:"process_type,omitempty"`
	// Rank (optional)
	Rank          string `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessStacksRequest) Reset() {
	*x = GetProcessStacksRequest{}
	mi := &file_v1_deeptrace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessStacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessStacksRequest) ProtoMessage() {}

func (x *GetProcessStacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessStacksRequest.ProtoReflect.Descriptor instead.
func (*GetProcessStacksRequest) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{7}
}

func (x *GetProcessStacksRequest) GetProcessType() ProcessType {
	if x != nil {
		return x.ProcessType
	}
	return ProcessType_PROCESS_UNSPECIFIED
}

func (x *GetProcessStacksRequest) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

// Process stack response
type ProcessStacksResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Processes        []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`                                        // Process information list
	TotalProcesses   int32                  `protobuf:"varint,2,opt,name=total_processes,json=totalProcesses,proto3" json:"total_processes,omitempty"`       // Total number of processes of this type
	SampledProcesses int32                  `protobuf:"varint,3,opt,name=sampled_processes,json=sampledProcesses,proto3" json:"sampled_processes,omitempty"` // Number of actually sampled processes
	SnapshotTime     string                 `protobuf:"bytes,4,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`              // Snapshot acquisition time
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessStacksResponse) Reset() {
	*x = ProcessStacksResponse{}
	mi := &file_v1_deeptrace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStacksResponse) ProtoMessage() {}

func (x *ProcessStacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStacksResponse.ProtoReflect.Descriptor instead.
func (*ProcessStacksResponse) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessStacksResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessStacksResponse) GetTotalProcesses() int32 {
	if x != nil {
		return x.TotalProcesses
	}
	return 0
}

func (x *ProcessStacksResponse) GetSampledProcesses() int32 {
	if x != nil {
		return x.SampledProcesses
	}
	return 0
}

func (x *ProcessStacksResponse) GetSnapshotTime() string {
	if x != nil {
		return x.SnapshotTime
	}
	return ""
}

// Error details
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=v1.ErrorCode" json:"code,omitempty"`                                                              // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // Error description
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Error context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_v1_deeptrace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_UNKNOWN
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type RestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_v1_deeptrace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{10}
}

func (x *RestartRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type RestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_v1_deeptrace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{11}
}

func (x *RestartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent version information response
type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	BuildTag      string                 `protobuf:"bytes,4,opt,name=build_tag,json=buildTag,proto3" json:"build_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_v1_deeptrace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{12}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *VersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *VersionResponse) GetBuildTag() string {
	if x != nil {
		return x.BuildTag
	}
	return ""
}

type GetAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                         // Start timestamp (optional)
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                               // End timestamp (optional)
	MinSeverity   Severity               `protobuf:"varint,3,opt,name=min_severity,json=minSeverity,proto3,enum=v1.Severity" json:"min_severity,omitempty"` // Minimum severity level
	Unprocessed   bool                   `protobuf:"varint,4,opt,name=unprocessed,proto3" json:"unprocessed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsRequest) Reset() {
	*x = GetAlertsRequest{}
	mi := &file_v1_deeptrace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsRequest) ProtoMessage() {}

func (x *GetAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsRequest) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{13}
}

func (x *GetAlertsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetAlertsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetAlertsRequest) GetMinSeverity() Severity {
	if x != nil {
		return x.MinSeverity
	}
	return Severity_INFO
}

func (x *GetAlertsRequest) GetUnprocessed() bool {
	if x != nil {
		return x.Unprocessed
	}
	return false
}

type AlertRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRecord) Reset() {
	*x = AlertRecord{}
	mi := &file_v1_deeptrace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRecord) ProtoMessage() {}

func (x *AlertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRecord.ProtoReflect.Descriptor instead.
func (*AlertRecord) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{14}
}

func (x *AlertRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AlertRecord) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

type GetAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*AlertRecord         `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	mi := &file_v1_deeptrace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_deeptrace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_v1_deeptrace_proto_rawDescGZIP(), []int{15}
}

func (x *GetAlertsResponse) GetAlerts() []*AlertRecord {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_v1_deeptrace_proto protoreflect.FileDescriptor

const file_v1_deeptrace_proto_rawDesc = "" +
	"\n" +
	"\x12v1/deeptrace.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\"\n" +
	"\x05level\x18\x02 \x01(\x0e2\f.v1.LogLevelR\x05level\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x05R\x05epoch\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xa7\x01\n" +
	"\aRankLog\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\tR\x04rank\x12&\n" +
	"\aentries\x18\x02 \x03(\v2\f.v1.LogEntryR\aentries\x12'\n" +
	"\x0fsuspend_seconds\x18\x03 \x01(\x05R\x0esuspendSeconds\x127\n" +
	"\ttail_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\btailTime\"N\n" +
	"\x14GetRecentLogsRequest\x12\x1b\n" +
	"\tmax_lines\x18\x01 \x01(\x05R\bmaxLines\x12\x19\n" +
	"\bwork_dir\x18\x02 \x01(\tR\aworkDir\"6\n" +
	"\vLogResponse\x12'\n" +
	"\branklogs\x18\x01 \x03(\v2\v.v1.RankLogR\branklogs\"n\n" +
	"\vThreadStack\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\x05R\bthreadId\x12\x1f\n" +
	"\vthread_name\x18\x02 \x01(\tR\n" +
	"threadName\x12!\n" +
	"\fstack_frames\x18\x03 \x03(\tR\vstackFrames\"\xb6\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.v1.ProcessTypeR\x04type\x12)\n" +
	"\athreads\x18\x04 \x03(\v2\x0f.v1.ThreadStackR\athreads\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\tR\x04rank\x12\x1d\n" +
	"\n" +
	"local_rank\x18\x06 \x01(\tR\tlocalRank\"a\n" +
	"\x0fProcessInfoList\x12-\n" +
	"\tprocesses\x18\x01 \x03(\v2\x0f.v1.ProcessInfoR\tprocesses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"a\n" +
	"\x17GetProcessStacksRequest\x122\n" +
	"\fprocess_type\x18\x01 \x01(\x0e2\x0f.v1.ProcessTypeR\vprocessType\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\tR\x04rank\"\xc1\x01\n" +
	"\x15ProcessStacksResponse\x12-\n" +
	"\tprocesses\x18\x01 \x03(\v2\x0f.v1.ProcessInfoR\tprocesses\x12'\n" +
	"\x0ftotal_processes\x18\x02 \x01(\x05R\x0etotalProcesses\x12+\n" +
	"\x11sampled_processes\x18\x03 \x01(\x05R\x10sampledProcesses\x12#\n" +
	"\rsnapshot_time\x18\x04 \x01(\tR\fsnapshotTime\"\xbe\x01\n" +
	"\vErrorDetail\x12!\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\acontext\x18\x03 \x03(\v2\x1c.v1.ErrorDetail.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eRestartRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"E\n" +
	"\x0fRestartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x12\x1b\n" +
	"\tbuild_tag\x18\x04 \x01(\tR\bbuildTag\"\xd7\x01\n" +
	"\x10GetAlertsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12/\n" +
	"\fmin_severity\x18\x03 \x01(\x0e2\f.v1.SeverityR\vminSeverity\x12 \n" +
	"\vunprocessed\x18\x04 \x01(\bR\vunprocessed\"\x8b\x01\n" +
	"\vAlertRecord\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\bseverity\x18\x03 \x01(\x0e2\f.v1.SeverityR\bseverity\"<\n" +
	"\x11GetAlertsResponse\x12'\n" +
	"\x06alerts\x18\x01 \x03(\v2\x0f.v1.AlertRecordR\x06alerts*n\n" +
	"\bLogLevel\x12\x13\n" +
	"\x0fLOG_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tLOG_DEBUG\x10\x01\x12\f\n" +
	"\bLOG_INFO\x10\x02\x12\x0f\n" +
	"\vLOG_WARNING\x10\x03\x12\r\n" +
	"\tLOG_ERROR\x10\x04\x12\x10\n" +
	"\fLOG_CRITICAL\x10\x05*j\n" +
	"\vProcessType\x12\x17\n" +
	"\x13PROCESS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROCESS_TRAINER\x10\x01\x12\x17\n" +
	"\x13PROCESS_DATA_LOADER\x10\x02\x12\x14\n" +
	"\x10PROCESS_LAUNCHER\x10\x03*\xb3\x01\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aERROR_INVALID_PROCESS_TYPE\x10\x01\x12\x1b\n" +
	"\x17ERROR_PROCESS_NOT_FOUND\x10\x02\x12\x1e\n" +
	"\x1aERROR_LOG_SOURCE_NOT_FOUND\x10\x03\x12\x1b\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\x04\x12\x19\n" +
	"\x15ERROR_SNAPSHOT_FAILED\x10\x05*:\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x032\x8f\x02\n" +
	"\x10DeepTraceService\x12:\n" +
	"\rGetRecentLogs\x12\x18.v1.GetRecentLogsRequest\x1a\x0f.v1.LogResponse\x12J\n" +
	"\x10GetProcessStacks\x12\x1b.v1.GetProcessStacksRequest\x1a\x19.v1.ProcessStacksResponse\x128\n" +
	"\rRestartServer\x12\x12.v1.RestartRequest\x1a\x13.v1.RestartResponse\x129\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\x13.v1.VersionResponse2J\n" +
	"\fAlertService\x12:\n" +
	"\tGetAlerts\x12\x14.v1.GetAlertsRequest\x1a\x15.v1.GetAlertsResponse\"\x00B\vZ\t../v1/;v1b\x06proto3"

var (
	file_v1_deeptrace_proto_rawDescOnce sync.Once
	file_v1_deeptrace_proto_rawDescData []byte
)

func file_v1_deeptrace_proto_rawDescGZIP() []byte {
	file_v1_deeptrace_proto_rawDescOnce.Do(func() {
		file_v1_deeptrace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_deeptrace_proto_rawDesc), len(file_v1_deeptrace_proto_rawDesc)))
	})
	return file_v1_deeptrace_proto_rawDescData
}

var file_v1_deeptrace_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_deeptrace_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_deeptrace_proto_goTypes = []any{
	(LogLevel)(0),                   // 0: v1.LogLevel
	(ProcessType)(0),                // 1: v1.ProcessType
	(ErrorCode)(0),                  // 2: v1.ErrorCode
	(Severity)(0),                   // 3: v1.Severity
	(*LogEntry)(nil),                // 4: v1.LogEntry
	(*RankLog)(nil),                 // 5: v1.RankLog
	(*GetRecentLogsRequest)(nil),    // 6: v1.GetRecentLogsRequest
	(*LogResponse)(nil),             // 7: v1.LogResponse
	(*ThreadStack)(nil),             // 8: v1.ThreadStack
	(*ProcessInfo)(nil),             // 9: v1.ProcessInfo
	(*ProcessInfoList)(nil),         // 10: v1.ProcessInfoList
	(*GetProcessStacksRequest)(nil), // 11: v1.GetProcessStacksRequest
	(*ProcessStacksResponse)(nil),   // 12: v1.ProcessStacksResponse
	(*ErrorDetail)(nil),             // 13: v1.ErrorDetail
	(*RestartRequest)(nil),          // 14: v1.RestartRequest
	(*RestartResponse)(nil),         // 15: v1.RestartResponse
	(*VersionResponse)(nil),         // 16: v1.VersionResponse
	(*GetAlertsRequest)(nil),        // 17: v1.GetAlertsRequest
	(*AlertRecord)(nil),             // 18: v1.AlertRecord
	(*GetAlertsResponse)(nil),       // 19: v1.GetAlertsResponse
	nil,                             // 20: v1.ErrorDetail.ContextEntry
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 22: google.protobuf.Empty
}
var file_v1_deeptrace_proto_depIdxs = []int32{
	21, // 0: v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: v1.LogEntry.level:type_name -> v1.LogLevel
	4,  // 2: v1.RankLog.entries:type_name -> v1.LogEntry
	21, // 3: v1.RankLog.tail_time:type_name -> google.protobuf.Timestamp
	5,  // 4: v1.LogResponse.ranklogs:type_name -> v1.RankLog
	1,  // 5: v1.ProcessInfo.type:type_name -> v1.ProcessType
	8,  // 6: v1.ProcessInfo.threads:type_name -> v1.ThreadStack
	9,  // 7: v1.ProcessInfoList.processes:type_name -> v1.ProcessInfo
	1,  // 8: v1.GetProcessStacksRequest.process_type:type_name -> v1.ProcessType
	9,  // 9: v1.ProcessStacksResponse.processes:type_name -> v1.ProcessInfo
	2,  // 10: v1.ErrorDetail.code:type_name -> v1.ErrorCode
	20, // 11: v1.ErrorDetail.context:type_name -> v1.ErrorDetail.ContextEntry
	21, // 12: v1.GetAlertsRequest.start_time:type_name -> google.protobuf.Timestamp
	21, // 13: v1.GetAlertsRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 14: v1.GetAlertsRequest.min_severity:type_name -> v1.Severity
	21, // 15: v1.AlertRecord.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 16: v1.AlertRecord.severity:type_name -> v1.Severity
	18, // 17: v1.GetAlertsResponse.alerts:type_name -> v1.AlertRecord
	6,  // 18: v1.DeepTraceService.GetRecentLogs:input_type -> v1.GetRecentLogsRequest
	11, // 19: v1.DeepTraceService.GetProcessStacks:input_type -> v1.GetProcessStacksRequest
	14, // 20: v1.DeepTraceService.RestartServer:input_type -> v1.RestartRequest
	22, // 21: v1.DeepTraceService.GetVersion:input_type -> google.protobuf.Empty
	17, // 22: v1.AlertService.GetAlerts:input_type -> v1.GetAlertsRequest
	7,  // 23: v1.DeepTraceService.GetRecentLogs:output_type -> v1.LogResponse
	12, // 24: v1.DeepTraceService.GetProcessStacks:output_type -> v1.ProcessStacksResponse
	15, // 25: v1.DeepTraceService.RestartServer:output_type -> v1.RestartResponse
	16, // 26: v1.DeepTraceService.GetVersion:output_type -> v1.VersionResponse
	19, // 27: v1.AlertService.GetAlerts:output_type -> v1.GetAlertsResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_v1_deeptrace_proto_init() }
func file_v1_deeptrace_proto_init() {
	if File_v1_deeptrace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_deeptrace_proto_rawDesc), len(file_v1_deeptrace_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_deeptrace_proto_goTypes,
		DependencyIndexes: file_v1_deeptrace_proto_depIdxs,
		EnumInfos:         file_v1_deeptrace_proto_enumTypes,
		MessageInfos:      file_v1_deeptrace_proto_msgTypes,
	}.Build()
	File_v1_deeptrace_proto = out.File
	file_v1_deeptrace_proto_goTypes = nil
	file_v1_deeptrace_proto_depIdxs = nil
}
